apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
      otlp:
        protocols:
          grpc:
            #endpoint: otel-collector.otel.svc.cluster.local:4317
            endpoint: ${env:MY_POD_IP}:4317
          http:
            #endpoint: otel-collector.grafana-lab.svc.cluster.local:4318
            endpoint: ${env:MY_POD_IP}:4318

    exporters:
      # https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/loggingexporter/README.md
      logging:
        verbosity: normal

      # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md
      loki:
        endpoint: http://loki-gateway.grafana-lab.svc.cluster.local/loki/api/v1/push
        tls:
          insecure: true

      # https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md
      otlp/tempo:
        endpoint: http://tempo-distributor.grafana-lab.svc.cluster.local:4317
        tls:
          insecure: true

      otlp/elastic:
        # endpoint: https://apm.elastic-system.svc.cluster.local:8200
        # endpoint: https://apm.elastic-system.svc:8200
        endpoint: http://apm.elastic-system.svc:8200
        headers:
          # should be replace to your elastic-agent token
          Authorization: "Bearer <token>"
        tls:
          insecure: true

    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 683

    processors:
      batch:

      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s

      # for tempo
      resource:
        attributes:
          - action: insert
            key: service_name
            from_attribute: service.name
          - action: insert
            key: service_env
            from_attribute: service.env
          - action: insert
            key: service_namespace
            from_attribute: service.namespace
          - action: insert
            key: service_version
            from_attribute: service.version
          - action: insert
            key: loki.resource.labels
            value: service_name, service_env, service_namespace, service_version

    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        logs:
          receivers: [otlp]
          processors: []
          exporters: [logging, otlp/elastic]
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, otlp/elastic]
