# ref: https://github.com/rabbitmq/cluster-operator/blob/main/observability/prometheus/monitors/rabbitmq-cluster-operator-podmonitor.yml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rabbitmq-cluster-operator
  # If labels are defined in spec.podMonitorSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
spec:
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq-operator
  namespaceSelector:
    matchNames:
    - rabbitmq-system