apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
resources:
  - rabbitmq-cluster.yaml
  - rabbitmq-prometheus-monitor.yml
# configMapGenerator:
#   - name: rabbitmq-definitions-configmap
#     files:
#     - rabbitmq_definitions.json
generatorOptions:
  disableNameSuffixHash: true