apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
resources:
  - rabbitmq-cluster.yaml
  - rabbitmq-prometheus-monitor.yaml
  # 以下兩個是 istio 的網路設定，依需求同步
  - rabbitmq-istio-gateway.yaml
  - rabbitmq-istio-vs.yaml
# configMapGenerator:
#   - name: rabbitmq-definitions-configmap
#     files:
#     - rabbitmq_definitions.json
generatorOptions:
  disableNameSuffixHash: true